/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic05CYWg5a0R2MGluL2ZSM3QvMjB6Tk9qL3NUK3VBR1FEeDFIOEc1b2VXbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK01LMTAwZERGWFBBTlU5bEVMcmRFRHZoOEF0am4xc3J2N0U2ay9LMlpVST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJxQ3MwRHdUME9VTXA5UHFWcTljQllNNFhKRVp6TUVNZGRNNTZyR1dvUUdzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2R1hkTXVmM0toUXBTek03S2g2VlFycGdjOGNaNitHUllFUjJrYm9TSEJBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdNU2JDcTB3cUFIYzFDcmhlWk82dENRaFBVMUQ3d3RBd0o5TC91a3FBMXc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkY2MmdkVWxWTlJjemh0R1JjZDZiM0FwNFBWdUhjeUJ6ZGp5NENTa0doQmM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE9sbjZOMG1pTHpyOE5oNXFWb0pKbkhFQ3NUVU1iYTY1cnl0S3JHdkFVTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSHAwdTdGeUFpWVdsbkMrS0xCUHVseUdORmkwNkZ6ajc2clNLTysyMnFnVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1tWTJvQ3FaS0RlT1VHOEdOcnlPVWlmVnVWWVREcFpkYjBxNFZFY3hMNnhlQTM4eUdEMnBXQm9uM0xtL0x5VzJMZGJiQkgrYXAwbE1ORGJCblQwbmhBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NywiYWR2U2VjcmV0S2V5IjoiRzliS250THRIVkZOU1BpeUVLVDY1NUhwOHdKRFdmVEJuWEdBeFVJZXVNYz0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOltdLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoidWE5QkFPZ29Sc3VWT3NkTzZVeGE3ZyIsInBob25lSWQiOiIyMzQ5MGQwNy1hZjc3LTQyY2UtODRiYi03YmJlY2MxMGFjYWQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidDRET1Z2YW52T0ovMWRTVnM4UngwM09DNjlBPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlhKTWloV1NNSnRWWDdQMDZ3OVVmTDlRemtxZz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJLSFg4Q0U3UyIsIm1lIjp7ImlkIjoiOTQ3NDE1NjQ1ODM6MzZAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0lUTDNMY0NFTnJHMXJrR0dDd2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlFqSk1VcjJEQlYrTzlESnBRUlBWYWlEcXZVc2pNdDVBUnJkNkgrc0RsMjQ9IiwiYWNjb3VudFNpZ25hdHVyZSI6InFCSGxLZ0NITjR0TDM2eGRTTHJ6OU5JQjVpekJWREYxd1N6aVpmYVFYeWhPZFd5am1yZHhQTTVhaWw1RVJoK295TjN2YTJjd1hpTmlKK0VnbTN2cEFBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJXbGlIcW8wT01LUEpyd2s0TlpjbWNuUlBXNm44UkpOakFxMDg5SkMzaEVxSy9hT29Ra3lpUHE3aEltVDVjeXAzNzlzTG9oaVBMemFOc3ZaU2E3aHdpZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0NzQxNTY0NTgzOjM2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVJeVRGSzlnd1ZmanZReWFVRVQxV29nNnIxTEl6TGVRRWEzZWgvckE1ZHUifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE1Njg0ODZ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
